version: "3.9"

services:
  mariadb:
    image: mariadb:11.3
    container_name: demeter-mariadb
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: file_management
      MARIADB_USER: admin
      MARIADB_PASSWORD: admin
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - backend-net

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: demeter-backend
    ports:
      - "8000:8000"
    environment:
      DB_HOST: demeter-mariadb
      DB_NAME: file_management
    depends_on:
      - mariadb
    networks:
      - backend-net

volumes:
  mariadb_data:

networks:
  backend-net:
    driver: bridge
