version: '3.9'

services:
  mariadb:
    image: mariadb:11.3
    container_name: mariadb-local
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: file_management
      MARIADB_USER: test
      MARIADB_PASSWORD: password
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - backend-net

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi-backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app/src
    command: uv run uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - mariadb
    networks:
      - backend-net


networks:
  backend-net:
    driver: bridge
