services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./server/src:/app/src
    environment:
      - PYTHONPATH=/app/src
    command: uv run uvicorn main:app --host 0.0.0.0 --port 8000 --reload