
CREATE TABLE IF NOT EXISTS Comments (
    id int NOT NULL AUTO_INCREMENT PRIMARY KEY,
    user_id int NOT NULL,
    file_id int NOT NULL,
    content TEXT NOT NULL,
    CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES Users (id) ON DELETE CASCADE ON UPDATE RESTRICT,
    CONSTRAINT fk_file FOREIGN KEY (file_id) REFERENCES Files (id) ON DELETE CASCADE ON UPDATE RESTRICT
) ENGINE = InnoDB;
