
CREATE TABLE IF NOT EXISTS Files (
    id int NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name TEXT NOT NULL,
    dir_id int,
    data LONGTEXT NOT NULL,
    CONSTRAINT fk_dir FOREIGN KEY (dir_id) REFERENCES Dirs (id) ON DELETE CASCADE ON UPDATE RESTRICT
) ENGINE = InnoDB;
