name: Create Feature Branch

on:
    workflow_dispatch:
        inputs:
            issue_number:
                description: 'GitHub Issue Number'
                required: true
                type: string

jobs:
    create-feature-branch:
        runs-on: debian-latest

        steps:
        - 
            name: Checkout repository
            uses: actions/checkout@v3

        - 
            name: Create feature branch
            id: create_branch
            run: |
                ISSUE_NUMBER=${{ github.event.inputs.issue_number }}
                BRANCH_NAME="feature/issue-${ISSUE_NUMBER}"
                git fetch origin
                git checkout -b $BRANCH_NAME
                git push origin $BRANCH_NAME
                echo "branch_name=$BRANCH_NAME" >> $GITHUB_ENV

        - 
            name: Add comment to issue
            uses: peter-evans/create-or-update-comment@v3
            with:
                token: ${{ secrets.GITHUB_TOKEN }}
                issue-number: ${{ github.event.inputs.issue_number }}
                body: "Feature branch `feature/issue-${{ github.event.inputs.issue_number }}` has been created."
