name: Feature Merge Check

on:
    pull_request:
        types: [opened, synchronize, reopened]
        branches:
            - main

jobs:
    check-merge:
        if: github.event.pull_request.merged == true
        runs-on: ubuntu-latest

        steps:
            -
                name: Notify about merge
                run: echo "${GITHUB_ACTOR} has opened a pull request to merge the feature branch into main."
            -
                name: Check for merge conflicts
                run: |
                    git fetch origin main
                    git checkout main
                    git merge --no-commit --no-ff ${{ github.head_ref }} || echo "Merge conflicts detected"
                    git reset --hard HEAD
            -
                name: Notify about merge conflicts
                if: failure()
                run: echo "Merge conflicts detected. Please resolve them before merging."
            - 
                name: Server test
                run: |
                    echo "Running server tests..."
                    python3 -m venv venv
                    source venv/bin/activate
                    pip install -r server/requirements.txt
                    pytest server/src/tests
                    deactivate
                
            -
                name: Client test
                run: |
                    echo "Running client tests..."
                    cd client/src
                    npm install
                    npm start
