name: Test Code upon Pull Request

on:
    pull_request:
        types:
            - opened
            - synchronize
            - reopened
            - edited
            - ready_for_review

jobs: 
    test_pull_request:
        runs-on: ubuntu-latest

        permissions:
            contents: read
            pull-requests: write

        steps:

            -
                name: Check out repository
                uses: actions/checkout@v3

            -
                name: Run Server Tests
                run: |
                    chmod +x ./server/test.bash
                    bash -x
                    ./server/test.bash
                    
            -
                name: Run Client Tests
                run: |
                    chmod +x ./client/test.bash
                    bash -x
                    ./client/test.bash
